/// This file was generated by C# converter tool
/// Any changes made to this file manually will be lost next time the file is regenerated.

using System.Linq;
using TypeScript.CSharp;

namespace Demo
{
    public interface IGreeter
    {
        String greeting
        {
            get;
            set;
        }

        String greet();
    }
}